### ISSUE TITLE
more Pure Gamma steps

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Filters_MiSTer#14]
[Pure_Gamma_1.1_to_2.0.zip](https://github.com/MiSTer-devel/Filters_MiSTer/files/4002326/Pure_Gamma_1.1_to_2.0.zip)

**Comment by ghogan42** [comment]
I don't think these have a use but I added them anyway (well I will momentarily).  The normal 2.2 to 2.5 gamma adjustment requires around ~1.15 gamma. So something like gamma 2.0 doesn't seem to have a use case.
