### ISSUE TITLE
Poly Gamma Files Duplicated

### ISSUE THREAD

**Issue by Bits-n-Stuff** [MiSTer-devel/Filters_MiSTer#16]
Poly files listed inside the **Poly_Gamma** folder as well as in **Gamma** folder so duplicate when updating with script.
![Screen Shot 2020-06-19 at 22 11 51](https://user-images.githubusercontent.com/25779045/85180449-6bf28980-b27b-11ea-948a-3f05d0d58130.png)

**Comment by ghogan42** [comment]
Fixed in recent commit
