### ISSUE TITLE
Rename "Composite Blend"-filters?

### ISSUE THREAD

**Issue by ThreepwoodLeBrush** [MiSTer-devel/Filters_MiSTer#25]
The "Composite Blend"-filters, while being an honorable effort, do sadly not achieve a composite blend effect. Maybe it would be better to rename them to "HV Blur" or similar, to avoid confusion.

Please see this post: https://misterfpga.org/viewtopic.php?p=25475#p25475

**Comment by trashuncle** [comment]
The composite blend filters are actually kind of redundant (and I believe no longer included). 
If you use GS_Sharpness_000 it is the same effect, I believe.

**Comment by ThreepwoodLeBrush** [comment]
That is true and the now included "CRT Simulation" filter claiming to do composite, does actually blend. Thank you, I am closing my ticket.
