### ISSUE TITLE
Request - Pure Gamma 113 & 114

### ISSUE THREAD

**Issue by mjj03301977** [MiSTer-devel/Filters_MiSTer#29]
For those of us with modern calibrated flat panel displays to 2.2 gamma, it is my understanding that the proper gamma filter to use would be pure gamma 113 or 114 to try and achieve close to 2.5 gamma that CRTs typically used.

Would someone please make a 113 and 114 pure gamma filter?

Thank you!

**Comment by ghogan42** [comment]
I added a pure gamma_113 that is gamma calculated as gamm 2.5/2.2.
