### ISSUE TITLE
GS_Sharpness_000 Garbage Pixels

### ISSUE THREAD

**Issue by Jayde6** [MiSTer-devel/Filters_MiSTer#34]
If GS_Sharpness_000 to at least 050 is chosen as a vertical filter or selected with same as horizontal filter, garbage pixels will appear at the bottom of the screen. This happened both before and after the recent sanity check update. A rom doesn't have to be loaded to see it.

Cycling vertical crop will move it off screen if crop is enabled again. Before it was at the bottom of the screen even with crop on.

![PXL_20220108_151343107](https://user-images.githubusercontent.com/39748732/148649464-9a6d68d0-8eaf-4373-b2a1-5bb8593d91ee.jpg)

**Comment by ghogan42** [comment]
There isn't really a way to make garbage filters from a filter. The filter.txt files just give the weights used to average 4 pixels.

If:
Each row has 4 numbers
Rows add up to 128
There are 64 rows of numbers

then the filters are likely fine.

Probably the scaler is reading pixels that are not black from the framebuffer for some reason. There is no way to fix it by modifying the filters.  The blurrier filters are just using higher weights for pixels that are further away from the output pixel and that's probably where the non-black pixels are.

**Comment by Jayde6** [comment]
I see, it's pretty edge case to begin with, not many people would use that particular filter setup. Still weird behavior giving that it happens with no rom selected I wonder what the scaler is doing. Plus the fact that it will show up at the bottom of the screen with cropped video on and then move to the actual bottom of the games output if crop is turned off and back on. 

Anyway, thanks for looking into it.

**Comment by ghogan42** [comment]
I think it is just that the framebuffer isn't cleared out and some bad pixels get read. I think there may just fix itself because currently there is someone looking at a big regarding triple buffering and old frames being read and also there was a small complaint about bad pixels getting read on resolution changes or something. If either of those get fixed it may turn out to have something to do with this as well.
